config/urls.py
"""Django Config APP Urls"""

# Libraries
from django.urls import path, include
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static

# MDA urls
from .urls_mda import urlpatterns as urlpatterns_mda

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("pages.urls")),

    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
] + urlpatterns_mda + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# if settings.DEBUG:

pages/urls.py
"""URLS Config of Pages Main"""

# Libraries
from django.urls import path, include

# View
from .views import home_page

app_name = "pages"
urlpatterns = [
    path("", home_page, name="home"),
]

profemontenegroud/urls.py
"""All Urls of Profemontenegroud"""

# Libraries
from django.urls import path

# Views
from . import views


app_name = "profemontenegrouds"
urlpatterns = [
    # PeriphepalType
    path(
        "periphepaltypes/",
        views.ListPeriphepaltypeView.as_view(),
        name="periphepaltypes",
    ),
    path(
        "periphepaltypes/new/",
        views.PeriphepaltypeCreateView.as_view(),
        name="periphepaltype-new",
    ),
    path(
        "periphepaltypes/<int:pk>/edit/",
        views.PeriphepaltypeUpdateView.as_view(),
        name="periphepaltype-edit",
    ),
    path(
        "periphepaltypes/<int:pk>/delete/",
        views.delete_periphepaltype_view,
        name="periphepaltype-delete",
    ),

    # Periphepal
    path(
        "periphepals/",
        views.ListPeriphepalView.as_view(),
        name="periphepals",
    ),
    path(
        "periphepals/new/",
        views.PeriphepalCreateView.as_view(),
        name="periphepal-new",
    ),
    path(
        "periphepals/<int:pk>/edit/",
        views.PeriphepalUpdateView.as_view(),
        name="periphepal-edit",
    ),
    path(
        "periphepals/<int:pk>/delete/",
        views.delete_periphepal_view,
        name="periphepal-delete",
    ),

    # Camera
    path(
        "cameras/",
        views.ListCameraView.as_view(),
        name="cameras",
    ),
    path(
        "cameras/new/",
        views.CameraCreateView.as_view(),
        name="camera-new",
    ),
    path(
        "cameras/<int:pk>/edit/",
        views.CameraUpdateView.as_view(),
        name="camera-edit",
    ),
    path(
        "cameras/<int:pk>/delete/",
        views.delete_camera_view,
        name="camera-delete",
    ),

    # CameraPeriphepal
    path(
        "cameraperiphepals/",
        views.ListCameraperiphepalView.as_view(),
        name="cameraperiphepals",
    ),
    path(
        "cameraperiphepals/new/",
        views.CameraperiphepalCreateView.as_view(),
        name="cameraperiphepal-new",
    ),
    path(
        "cameraperiphepals/<int:pk>/edit/",
        views.CameraperiphepalUpdateView.as_view(),
        name="cameraperiphepal-edit",
    ),
    path(
        "cameraperiphepals/<int:pk>/delete/",
        views.delete_cameraperiphepal_view,
        name="cameraperiphepal-delete",
    ),

]

profemontenegroud/models/camera.py
"""Content Camera"""

# Libraries
from django.db import models

 # Modules


class Camera(models.Model):
    name = models.CharField("name", max_length=100, )

    def __str__(self):
        return f"Camera {self.pk}"

    def __repr__(self):
        return str(self)

profemontenegroud/models/cameraperiphepal.py
"""Content Cameraperiphepal"""

# Libraries
from django.db import models

 # Modules
from . import camera
from . import periphepal


class Cameraperiphepal(models.Model):
    camera = models.ForeignKey(camera.Camera, on_delete=models.CASCADE)
    periphepal = models.ForeignKey(periphepal.Periphepal, on_delete=models.CASCADE)

    def __str__(self):
        return f"Cameraperiphepal {self.pk}"

    def __repr__(self):
        return str(self)

profemontenegroud/models/periphepal.py
"""Content Periphepal"""

# Libraries
from django.db import models

 # Modules
from . import periphepaltype


class Periphepal(models.Model):
    name = models.CharField("name", max_length=100, )
    description = models.CharField("description", null=True, blank=True, max_length=200, )
    type_periphepal = models.ForeignKey(periphepaltype.Periphepaltype, on_delete=models.CASCADE)

    def __str__(self):
        return f"Periphepal {self.pk}"

    def __repr__(self):
        return str(self)

profemontenegroud/models/periphepaltype.py
"""Content Periphepaltype"""

# Libraries
from django.db import models

 # Modules


class Periphepaltype(models.Model):
    name = models.CharField("name", max_length=120, )
    description = models.CharField("description", max_length=200, )
    name_montenegro = models.CharField("name_montenegro", max_length=120, )

    def __str__(self):
        return f"Periphepaltype {self.pk}"

    def __repr__(self):
        return str(self)

profemontenegroud/forms.py
"""Forms of Profemontenegroud APP"""

# Libraries
from django import forms

# Models
from . import models

class PeriphepaltypeForm(forms.ModelForm):
    """Form to Periphepaltype"""

    class Meta:
        model = models.periphepaltype.Periphepaltype
        fields = ["name", "description", "name_montenegro", ]


class PeriphepalForm(forms.ModelForm):
    """Form to Periphepal"""
    type_periphepal = forms.ModelChoiceField(queryset=models.periphepaltype.Periphepaltype.objects.all())

    class Meta:
        model = models.periphepal.Periphepal
        fields = ["name", "description", "type_periphepal", ]


class CameraForm(forms.ModelForm):
    """Form to Camera"""

    class Meta:
        model = models.camera.Camera
        fields = ["name", ]


class CameraperiphepalForm(forms.ModelForm):
    """Form to Cameraperiphepal"""
    camera = forms.ModelChoiceField(queryset=models.camera.Camera.objects.all())
    periphepal = forms.ModelChoiceField(queryset=models.periphepal.Periphepal.objects.all())

    class Meta:
        model = models.cameraperiphepal.Cameraperiphepal
        fields = ["camera", "periphepal", ]

profemontenegroud/views.py
"""Views of Profemontenegroud"""

# Libraries
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.conf import settings
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Core
from core.views import FilteredListView

# App Contents
from . import models, filters, forms


# Periphepaltype

class ListPeriphepaltypeView(LoginRequiredMixin, FilteredListView):
    template_name = "periphepaltype/list.html"
    filterset_class = filters.PeriphepaltypeFilter
    model = models.periphepaltype.Periphepaltype
    paginate_by = settings.DEFAULT_COUNT_PAGINATE


class PeriphepaltypeCreateView(LoginRequiredMixin, generic.CreateView):
    """Create View Periphepaltype"""
    form_class = forms.PeriphepaltypeForm
    success_url = reverse_lazy("profemontenegrouds:periphepaltypes")
    template_name = "periphepaltype/new.html"


class PeriphepaltypeUpdateView(LoginRequiredMixin, generic.edit.UpdateView):
    """Update View Periphepaltype"""
    form_class = forms.PeriphepaltypeForm
    success_url = reverse_lazy("profemontenegrouds:periphepaltypes")
    template_name = "periphepaltype/new.html"

    def get_object(self, **kwargs):
        """Return data"""
        return get_object_or_404(models.periphepaltype.Periphepaltype, pk=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        """Modify Context"""
        context = super().get_context_data(**kwargs)
        context["is_update"] = True
        return context


@login_required
def delete_periphepaltype_view(request, pk):
    periphepaltype = get_object_or_404(models.periphepaltype.Periphepaltype, pk=pk)
    periphepaltype.delete()
    return redirect("profemontenegrouds:periphepaltypes")


# Periphepal

class ListPeriphepalView(LoginRequiredMixin, FilteredListView):
    template_name = "periphepal/list.html"
    filterset_class = filters.PeriphepalFilter
    model = models.periphepal.Periphepal
    paginate_by = settings.DEFAULT_COUNT_PAGINATE


class PeriphepalCreateView(LoginRequiredMixin, generic.CreateView):
    """Create View Periphepal"""
    form_class = forms.PeriphepalForm
    success_url = reverse_lazy("profemontenegrouds:periphepals")
    template_name = "periphepal/new.html"


class PeriphepalUpdateView(LoginRequiredMixin, generic.edit.UpdateView):
    """Update View Periphepal"""
    form_class = forms.PeriphepalForm
    success_url = reverse_lazy("profemontenegrouds:periphepals")
    template_name = "periphepal/new.html"

    def get_object(self, **kwargs):
        """Return data"""
        return get_object_or_404(models.periphepal.Periphepal, pk=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        """Modify Context"""
        context = super().get_context_data(**kwargs)
        context["is_update"] = True
        return context


@login_required
def delete_periphepal_view(request, pk):
    periphepal = get_object_or_404(models.periphepal.Periphepal, pk=pk)
    periphepal.delete()
    return redirect("profemontenegrouds:periphepals")


# Camera

class ListCameraView(LoginRequiredMixin, FilteredListView):
    template_name = "camera/list.html"
    filterset_class = filters.CameraFilter
    model = models.camera.Camera
    paginate_by = settings.DEFAULT_COUNT_PAGINATE


class CameraCreateView(LoginRequiredMixin, generic.CreateView):
    """Create View Camera"""
    form_class = forms.CameraForm
    success_url = reverse_lazy("profemontenegrouds:cameras")
    template_name = "camera/new.html"


class CameraUpdateView(LoginRequiredMixin, generic.edit.UpdateView):
    """Update View Camera"""
    form_class = forms.CameraForm
    success_url = reverse_lazy("profemontenegrouds:cameras")
    template_name = "camera/new.html"

    def get_object(self, **kwargs):
        """Return data"""
        return get_object_or_404(models.camera.Camera, pk=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        """Modify Context"""
        context = super().get_context_data(**kwargs)
        context["is_update"] = True
        return context


@login_required
def delete_camera_view(request, pk):
    camera = get_object_or_404(models.camera.Camera, pk=pk)
    camera.delete()
    return redirect("profemontenegrouds:cameras")


# Cameraperiphepal

class ListCameraperiphepalView(LoginRequiredMixin, FilteredListView):
    template_name = "cameraperiphepal/list.html"
    filterset_class = filters.CameraperiphepalFilter
    model = models.cameraperiphepal.Cameraperiphepal
    paginate_by = settings.DEFAULT_COUNT_PAGINATE


class CameraperiphepalCreateView(LoginRequiredMixin, generic.CreateView):
    """Create View Cameraperiphepal"""
    form_class = forms.CameraperiphepalForm
    success_url = reverse_lazy("profemontenegrouds:cameraperiphepals")
    template_name = "cameraperiphepal/new.html"


class CameraperiphepalUpdateView(LoginRequiredMixin, generic.edit.UpdateView):
    """Update View Cameraperiphepal"""
    form_class = forms.CameraperiphepalForm
    success_url = reverse_lazy("profemontenegrouds:cameraperiphepals")
    template_name = "cameraperiphepal/new.html"

    def get_object(self, **kwargs):
        """Return data"""
        return get_object_or_404(models.cameraperiphepal.Cameraperiphepal, pk=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        """Modify Context"""
        context = super().get_context_data(**kwargs)
        context["is_update"] = True
        return context


@login_required
def delete_cameraperiphepal_view(request, pk):
    cameraperiphepal = get_object_or_404(models.cameraperiphepal.Cameraperiphepal, pk=pk)
    cameraperiphepal.delete()
    return redirect("profemontenegrouds:cameraperiphepals")

profemontenegroud/templates/periphepaltype/list.html
{% extends 'content.html' %}{% load static %}{% load page %}

{% block container %}
<div class="title">
    <h3><i class="bi bi-clipboard-plus"></i> List of Periphepaltype</h3>
    <div class="general-actions">
      <a class="btn btn-primary" href="{% url 'profemontenegrouds:periphepaltype-new' %}">Create</a>
    </div>
  </div>

  <form class="form-filter" method="GET">
    <div class="filters">
{{ filterset.form.as_p }}    </div>
    <input class="btn btn-primary btn-large" type="submit" value="Filter" />
  </form>

  <div class="block">
{% if is_paginated %}      <div class="pagination">
        <p>
Page {{ page_obj.number }} of {{ paginator.num_pages }}        </p>
      </div>
{% endif %}    <div class="block-table">
      <table class="table table-responsive">
        <thead>
          <tr>
            <th scope="col">Id</th>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
            <th scope="col">Name_montenegro</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
{% for object in object_list %}          <tr>
              <td>
{{ object.id }}              </td>
              <td>{{ object.name }}</td>
              <td>{{ object.description }}</td>
              <td>{{ object.name_montenegro }}</td>
              <td>
                <a class="btn btn-secondary btn-small" href="{% url 'profemontenegrouds:periphepaltype-edit' pk=object.pk %}"><i class="bi bi-pencil-fill"></i></a>
                <a class="btn btn-danger btn-small" href="{% url 'profemontenegrouds:periphepaltype-delete' pk=object.pk %}"><i class="bi bi-trash-fill"></i></i></a>
              </td>
            </tr>
{% endfor %}        </tbody>
      </table>
    </div>


    {% if is_paginated %}
      <div class="page-buttons">
        {% if page_obj.has_previous %}
          <a class="btn btn-secondary" href="?{% param_replace page=page_obj.previous_page_number %}"><i class="bi bi-chevron-compact-left"></i></a>
        {% endif %}
        {% if page_obj.has_next %}
          <a class="btn btn-secondary" href="?{% param_replace page=page_obj.next_page_number %}"><i class="bi bi-chevron-compact-right"></i></a>
          {% endif %}
      </div>
      {% endif %}
  </div>

  {% endblock container %}

profemontenegroud/templates/periphepaltype/new.html
{% extends "content.html" %}
{% load static %}


{% block container %}
  <div class="title">
    <h3>{% if is_update %}<i class="bi bi-pencil-square"></i> Update Periphepaltype {{ object.pk }}{% else %}<i class="bi bi-clipboard-plus"></i> Create New Periphepaltype{% endif %}</h3>
  </div>

  <div class="block">
    <form method="POST" enctype="multipart/form-data">
{% csrf_token %}      <div class="input-field col s12">
        <label for="name">{{ form.name.label }}</label>
{{ form.name }}      </div>
      <div class="input-field col s12">
        <label for="description">{{ form.description.label }}</label>
{{ form.description }}      </div>
      <div class="input-field col s12">
        <label for="name_montenegro">{{ form.name_montenegro.label }}</label>
{{ form.name_montenegro }}      </div>
      <div class="buttons">
        <a class="btn btn-secondary" href="{% if is_update %}{% url 'profemontenegrouds:periphepaltype-edit' pk=object.pk %}{% else %}{% url 'profemontenegrouds:periphepaltype-new' %}{% endif %}">Cancel</a>
        <input class="btn btn-primary" type="submit" value="{% if is_update %}Update{% else %}Save{% endif %}">
      </div>
    </form>
  </div>

{% endblock container %}