accounts/urls.py
"""Accounts Session of User"""

# Libraries
from django.urls import path

# Views
from . import views


app_name = "accounts"
urlpatterns = [
    path(
        "users/",
        views.ListProfileView.as_view(),
        name="users"
    ),

    path(
        "users/new",
        views.SignUpView.as_view(),
        name="profile-new"
    ),

    path(
        "users/<str:username>/",
        views.ShowProfileView.as_view(),
        name="profile-username"
    ),

    path(
        "users/<str:username>/block/",
        views.block_user,
        name="profile-username-block"
    ),
    path(
        "users/<str:username>/unblock/",
        views.unlock_user,
        name="profile-username-unblock"
    ),
    path(
        "users/<str:username>/delete/",
        views.delete_user,
        name="profile-username-delete"
    ),

    path(
        "me/edit",
        views.UpdateProfileView.as_view(),
        name="profile-user-edit"
    ),

    path(
        "me/",
        views.show_profile,
        name="profile-user",
    ),
]

config/urls.py
"""Django Config APP Urls"""

# Libraries
from django.urls import path, include
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static

# MDA urls
from .urls_mda import urlpatterns as urlpatterns_mda

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("pages.urls")),

    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
] + urlpatterns_mda + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# if settings.DEBUG:

pages/urls.py
"""URLS Config of Pages Main"""

# Libraries
from django.urls import path, include

# View
from .views import home_page

app_name = "pages"
urlpatterns = [
    path("", home_page, name="home"),
]

profemontenegroud/urls.py
"""All Urls of Profemontenegroud"""

# Libraries
from django.urls import path

# Views
from . import views


app_name = "profemontenegrouds"
urlpatterns = [
    # PeriphepalType
    path(
        "periphepaltypes/",
        views.ListPeriphepaltypeView.as_view(),
        name="periphepaltypes",
    ),
    path(
        "periphepaltypes/new/",
        views.PeriphepaltypeCreateView.as_view(),
        name="periphepaltype-new",
    ),
    path(
        "periphepaltypes/<int:pk>/edit/",
        views.PeriphepaltypeUpdateView.as_view(),
        name="periphepaltype-edit",
    ),
    path(
        "periphepaltypes/<int:pk>/delete/",
        views.delete_periphepaltype_view,
        name="periphepaltype-delete",
    ),

    # Periphepal
    path(
        "periphepals/",
        views.ListPeriphepalView.as_view(),
        name="periphepals",
    ),
    path(
        "periphepals/new/",
        views.PeriphepalCreateView.as_view(),
        name="periphepal-new",
    ),
    path(
        "periphepals/<int:pk>/edit/",
        views.PeriphepalUpdateView.as_view(),
        name="periphepal-edit",
    ),
    path(
        "periphepals/<int:pk>/delete/",
        views.delete_periphepal_view,
        name="periphepal-delete",
    ),

    # Camera
    path(
        "cameras/",
        views.ListCameraView.as_view(),
        name="cameras",
    ),
    path(
        "cameras/new/",
        views.CameraCreateView.as_view(),
        name="camera-new",
    ),
    path(
        "cameras/<int:pk>/edit/",
        views.CameraUpdateView.as_view(),
        name="camera-edit",
    ),
    path(
        "cameras/<int:pk>/delete/",
        views.delete_camera_view,
        name="camera-delete",
    ),

    # CameraPeriphepal
    path(
        "cameraperiphepals/",
        views.ListCameraperiphepalView.as_view(),
        name="cameraperiphepals",
    ),
    path(
        "cameraperiphepals/new/",
        views.CameraperiphepalCreateView.as_view(),
        name="cameraperiphepal-new",
    ),
    path(
        "cameraperiphepals/<int:pk>/edit/",
        views.CameraperiphepalUpdateView.as_view(),
        name="cameraperiphepal-edit",
    ),
    path(
        "cameraperiphepals/<int:pk>/delete/",
        views.delete_cameraperiphepal_view,
        name="cameraperiphepal-delete",
    ),

]

templates/components/footer.html
<footer class="container-fluid text-center text-white">
  <!-- Grid container -->
  <div class="container p-4 pb-0">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a class="btn btn-outline-light btn-floating m-1 social-button" href="#!" role="button"
      ><i class="fab fa-facebook-f"></i></a>

      <!-- Twitter -->
      <a class="btn btn-outline-light btn-floating m-1 social-button" href="#!" role="button"
      ><i class="fab fa-twitter"></i
                                 ></a>

      <!-- Google -->
      <a class="btn btn-outline-light btn-floating m-1 social-button" href="#!" role="button"
        ><i class="fab fa-google"></i></a>

      <!-- Instagram -->
      <a class="btn btn-outline-light btn-floating m-1 social-button" href="#!" role="button"
      ><i class="fab fa-instagram"></i></a>

      <!-- Linkedin -->
      <a class="btn btn-outline-light btn-floating m-1 social-button" href="#!" role="button"
      ><i class="fab fa-linkedin-in"></i></a>

      <!-- Github -->
      <a class="btn btn-outline-light btn-floating m-1 social-button" href="#!" role="button"
      ><i class="fab fa-github"></i></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3">
    © 2021 Copyright:
    <a class="text-white" href="https://vmgabriel.com">Developer</a>
  </div>
  <!-- Copyright -->
</footer>

templates/components/header.html
{% load static %}

<header class="header" id="header">
  <div class="nav_list header_toggle menu" id="menu">
    <i class='bi bi-list' id="header-toggle"></i>
  </div>
  <div class="header_img" data-bs-toggle="collapse" data-bs-target="#profile" aria-controls="profile" aria-expanded="false" aria-label="Toggle navigation">
    <img src="{% if user.image %}{{ user.image.url }}{% else %}{% static 'img/user.png' %}{% endif %}">
  </div>
</header>
<div class="collapse navbar-collapse profile-collapse" id="profile" style="width: 100%;">
  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
    <li class="nav-item">
      <i class="bi bi-person-fill"></i>
      <a class="nav-link" aria-current="page" href="{% url 'accounts:profile-user' %}">Profile</a>
    </li>
    <li class="nav-item">
      <i class="bi bi-door-open-fill"></i>
      <a class="nav-link" href="{% url 'logout' %}">Sign out</a>
    </li>
  </ul>
</div>

templates/components/nav.html
<a href="{% url 'profemontenegrouds:periphepaltypes' %}" class="nav_link">
  <i class='bi bi-palette-fill nav_icon'></i>
  <span class="nav_name">Periphepaltype</span>
</a>
<a href="{% url 'profemontenegrouds:periphepals' %}" class="nav_link">
  <i class='bi bi-palette-fill nav_icon'></i>
  <span class="nav_name">Periphepal</span>
</a>
<a href="{% url 'profemontenegrouds:cameras' %}" class="nav_link">
  <i class='bi bi-palette-fill nav_icon'></i>
  <span class="nav_name">Camera</span>
</a>
<a href="{% url 'profemontenegrouds:cameraperiphepals' %}" class="nav_link">
  <i class='bi bi-palette-fill nav_icon'></i>
  <span class="nav_name">Cameraperiphepal</span>
</a>

templates/components/navbar.html
{% load static %}

<div class="l-navbar" id="nav-bar">
  <nav class="nav">
    <div>
      <div class="nav_list nav_brand">
        <a href="{% url 'pages:home' %}" class="nav_link">
          <i class="bi bi-house-fill nav_icon"></i>
          <span class="nav_name">Project</span>
        </a>
      </div>
      <div class="nav_list">
        <a href="{% url 'accounts:users' %}" class="nav_link">
          <i class='bi bi-people-fill nav_icon'></i>
          <span class="nav_name">Users</span>
        </a>
        {% include "components/nav.html" %}
      </div>
    </div>
  </nav>
</div>