accounts/urls.py
"""Accounts Session of User"""

# Libraries
from django.urls import path

# Views
from . import views


app_name = "accounts"
urlpatterns = [
    path(
        "users/",
        views.ListProfileView.as_view(),
        name="users"
    ),

    path(
        "users/new",
        views.SignUpView.as_view(),
        name="profile-new"
    ),

    path(
        "users/<str:username>/",
        views.ShowProfileView.as_view(),
        name="profile-username"
    ),

    path(
        "users/<str:username>/block/",
        views.block_user,
        name="profile-username-block"
    ),
    path(
        "users/<str:username>/unblock/",
        views.unlock_user,
        name="profile-username-unblock"
    ),
    path(
        "users/<str:username>/delete/",
        views.delete_user,
        name="profile-username-delete"
    ),

    path(
        "me/edit",
        views.UpdateProfileView.as_view(),
        name="profile-user-edit"
    ),

    path(
        "me/",
        views.show_profile,
        name="profile-user",
    ),
]

config/urls.py
"""Django Config APP Urls"""

# Libraries
from django.urls import path, include
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static

# MDA urls
from .urls_mda import urlpatterns as urlpatterns_mda

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("pages.urls")),

    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
] + urlpatterns_mda + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# if settings.DEBUG:

pages/urls.py
"""URLS Config of Pages Main"""

# Libraries
from django.urls import path, include

# View
from .views import home_page

app_name = "pages"
urlpatterns = [
    path("", home_page, name="home"),
]

accounts/models.py
"""Models of account"""

# Libraries
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin, Group
from django.utils import timezone

from versatileimagefield.fields import VersatileImageField, PPOIField


class UserManager(BaseUserManager):
    """Creation of User - Manager"""
    def create_user(
            self,
            email=None,
            username=None,
            password=None,
            first_name=None,
            last_name=None,
            is_staff=None,
            telephone=None,
            groups=None,
            **kwargs
    ):
        """Create User"""
        email = UserManager.normalize_email(email.lower())
        user = self.model(
            email=email,
            username=username,
            first_name=first_name,
            telephone=telephone,
            is_staff=is_staff,
            **kwargs
        )
        if last_name:
            user.last_name = last_name
        if password:
            user.set_password(password)
        if groups:
            user.groups = groups
        user.save()
        return user

    def create_superuser(
            self, email, password=None, first_name=None, last_name=None, groups=None, username: str = None, **kwargs
    ):
        """Creation of superuser"""
        return self.create_user(
            email=email,
            username=username,
            password=password,
            first_name=first_name,
            last_name=last_name,
            groups=groups,
            is_staff=True,
            is_superuser=True,
            **kwargs
        )


class User(PermissionsMixin, AbstractBaseUser):
    """User Main Model"""
    email = models.EmailField("Email", unique=True)
    username = models.CharField("Username", unique=True, max_length=128)
    first_name = models.CharField("First Name", max_length=256)
    last_name = models.CharField("Last Name", max_length=256, blank=True)
    is_staff = models.BooleanField("Staff Status", default=False)
    inactive_at = models.DateField(blank=True, null=True)
    date_joined = models.DateTimeField("Date Joined", default=timezone.now, editable=False)
    telephone = models.CharField("Phone Number", max_length=30, blank=True, null=True)
    blocked_at = models.DateTimeField(blank=True, null=True)
    language_code = models.CharField(max_length=10, default=settings.LANGUAGE_CODE)
    image = VersatileImageField(
        upload_to="images/users",
        ppoi_field="ppoi",
        blank=True,
        verbose_name="image"
    )
    ppoi = PPOIField(verbose_name="ppoi")
    groups = models.ManyToManyField(Group, verbose_name="Groups", related_name="user_groups", blank=True)

    objects = UserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["first_name", "telephone", "username"]

    class Meta:
        """Meta Class Intern"""
        verbose_name = "User"
        verbose_name_plural = "Users"
        db_table = "user"

accounts/forms.py
"""Forms for user"""

# Libraries
from django import forms
from django.core.mail import send_mail
from versatileimagefield.forms import SizedImageCenterpointClickBootstrap3Field
from django.contrib.auth.forms import UserCreationForm
from django.conf import settings

# Models
from .models import User

EMAIL_CONTENT = """
Welcome to platform,

email: {email}
password: {password}

Please, change the password when you signup.
"""


class RegisterForm(forms.ModelForm):
    """Register Form"""
    class Meta:
        model = User
        fields = ("username", "email", "first_name", "last_name", "telephone")

    def save(self, commit=True):
        password = User.objects.make_random_password()
        user = super().save(commit=False)
        user.set_password(password)
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        user.email = self.cleaned_data["email"]
        user.telephone = self.cleaned_data["telephone"]

        if commit:
            if settings.SEND_EMAIL:
                send_mail(
                    subject=f"Welcome to platform {user.first_name}",
                    from_email=settings.DEFAULT_FROM_EMAIL,
                    message=EMAIL_CONTENT.format(email=user.email, password=password),
                    recipient_list=[user.email],
                    fail_silently=False,
                )
            user.save()
        return user


class UserForm(forms.ModelForm):
    """User Base Form Related Model"""
    # image = SizedImageCenterpointClickBootstrap3Field(required=False)

    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "telephone", "image"]

accounts/views.py
"""Created Views of Accounts Application"""

# Libraries
from datetime import datetime
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.views import generic
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings

# Forms
from .forms import UserForm, RegisterForm

# Models
from .models import User

# Filters
from .filters import ProfileFilter

# Core
from core.views import FilteredListView


class SignUpView(LoginRequiredMixin, generic.CreateView):
    """Create View Sign Up of account"""
    form_class = RegisterForm
    success_url = reverse_lazy("accounts:users")
    template_name = "signup.html"


class UpdateProfileView(LoginRequiredMixin, generic.edit.UpdateView):
    """Update profile view."""
    template_name = "profiles/edit.html"
    success_url = reverse_lazy('accounts:profile-user')
    form_class = UserForm
    model = User

    def get_object(self):
        """Return user"""
        return self.request.user


class ListProfileView(LoginRequiredMixin, FilteredListView):
    template_name = "profiles/list.html"
    filterset_class = ProfileFilter
    model = User
    paginate_by = settings.DEFAULT_COUNT_PAGINATE


@login_required
def show_profile(request):
    template = "profiles/show.html"
    return render(
        request,
        template,
        context={"user_data": request.user, "me": True}
    )


@login_required
def block_user(request, username: str):
    user = get_object_or_404(User, username=username)
    user.blocked_at = datetime.now()
    user.save()
    return redirect("accounts:users")


@login_required
def unlock_user(request, username: str):
    user = get_object_or_404(User, username=username)
    user.blocked_at = None
    user.save()
    return redirect("accounts:users")


@login_required
def delete_user(request, username: str):
    user = get_object_or_404(User, username=username)
    user.inactive_at = datetime.now()
    user.save()
    return redirect("accounts:users")


class ShowProfileView(LoginRequiredMixin, generic.DetailView):
    template_name = "profiles/show.html"
    context_object_name  = "user_data"
    slug_field = "username"
    slug_url_kwarg = "username"

    model = User

    def get_context_data(self, **kwargs):
        return super().get_context_data(**kwargs)

accounts/templates/profiles/edit.html
{% extends 'content.html' %}
{% load static %}

{% block container %}
  <div class="title">
    <h3>User Profile Edit - {{ object.username }}</h3>
  </div>
  <div class="block">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="input-field col s12">
        <label for="username">{{ form.username.label }}</label>
        {{ form.username }}
      </div>
      <div class="input-field col s12">
        <label for="first_name">{{ form.first_name.label }}</label>
        {{ form.first_name }}
      </div>
      <div class="input-field col s12">
        <label for="last_name">{{ form.last_name.label }}</label>
        {{ form.last_name }}
      </div>
      <div class="input-field col s12">
        <label for="telephone">{{ form.telephone.label }}</label>
        {{ form.telephone }}
      </div>
      <div class="input-field col s12">
        <label for="image">{{ form.image.label }}</label>
        {{ form.image }}
      </div>
      <div class="buttons">
        <a class="btn btn-secondary" href="{% url 'accounts:profile-user-edit' %}">Cancel</a>
        <button class="btn btn-primary" type="submit">Update</button>
      </div>
    </form>
  </div>
{% endblock container %}

accounts/templates/profiles/list.html
{% extends 'content.html' %}
{% load static %}
{% load page %}

{% block container %}
  <div class="title">
    <h3><i class="bi bi-people-fill"></i> List of User</h3>
    <div class="general-actions">
      <a class="btn btn-primary" href="{% url 'accounts:profile-new' %}">Create</a>
    </div>
  </div>

  <form class="form-filter" method="GET">
    <div class="filters">
      {{ filterset.form.as_p }}
    </div>
    <input class="btn btn-primary btn-large" type="submit" value="Filter" />
  </form>

  <div class="block">
    {% if is_paginated %}
      <div class="pagination">
        <p>
          Page {{ page_obj.number }} of {{ paginator.num_pages }}
        </p>
      </div>
    {% endif %}
    <div class="block-table">
      <table class="table table-responsive">
        <thead>
          <tr>
            <th scope="col"></th>
            <th scope="col">Username</th>
            <th scope="col">Full Name</th>
            <th scope="col">Telephone</th>
            <th scope="col">Status</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for user in object_list %}
            <tr>
              <td><img class="header_img" alt="image of user" src="{% if user.image %}{{ user.image.url }}{% else %}{% static 'img/user.png' %}{% endif %}"/></td>
              <td>{{ user.username }}</td>
              <td>{{ user.first_name }} {{ user.last_name }}</td>
              <td>{{ user.telephone }}</td>
              <td>
                <div class="badges">
                  {% if user.is_superuser %}
                    <span class="badge bg-success">Admin</span>
                  {% endif %}
                  {% if user.is_staff %}
                    <span class="badge bg-warning">Staff</span>
                  {% endif %}
                  {% if user.blocked_at %}
                    <span class="badge bg-danger">Blocked</span>
                  {% endif %}
                  {% if user.inactive_at %}
                    <span class="badge bg-dark">Inactive</span>
                  {% endif %}
                </div>
              </td>
              <td>
                <a class="btn btn-secondary btn-small" href="{% url 'accounts:profile-username' username=user.username %}"><i class="bi bi-eye-fill"></i></a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>

    {% if is_paginated %}
      <div class="page-buttons">
        {% if page_obj.has_previous %}
          <a class="btn btn-secondary" href="?{% param_replace page=page_obj.previous_page_number %}"><i class="bi bi-chevron-compact-left"></i></a>
        {% endif %}
        {% if page_obj.has_next %}
          <a class="btn btn-secondary" href="?{% param_replace page=page_obj.next_page_number %}"><i class="bi bi-chevron-compact-right"></i></a>
        {% endif %}
      </div>
    {% endif %}
  </div>
{% endblock container %}

accounts/templates/profiles/new.html
{% extends 'content.html' %}
{% load static %}

{% block container %}
  <p>Content for New</p>
{% endblock container %}

accounts/templates/profiles/show.html
{% extends "content.html" %}
{% load static %}

{% block container %}
  <div class="title">
    <h3>My Profile</h3>
  </div>
  <div class="block">
    <div class="title">
      <h6>Basic Information</h6>
      <div class="badges">
        {% if user_data.is_superuser %}
          <span class="badge bg-success">Admin</span>
        {% endif %}
        {% if user_data.is_staff %}
          <span class="badge bg-warning">Staff</span>
        {% endif %}
        {% if user_data.blocked_at %}
          <span class="badge bg-danger">Blocked</span>
        {% endif %}
        {% if user_data.inactive_at %}
          <span class="badge bg-dark">Inactive</span>
        {% endif %}
      </div>
    </div>
    <div class="inf">
      <div class="center-image">
        <img class="user_image" alt="user image" src="{% if user_data.image %}{{ user_data.image.url }}{% else %}{% static 'img/user.png' %}{% endif %}"/>
      </div>
    </div>
    <div class="inf">
      <h3>Username</h3>
      <p>{{ user_data.username }}</p>
    </div>
    <div class="inf">
      <h3>Full name</h3>
      <p>{{ user_data.first_name }} {{ user_data.last_name }}</p>
    </div>
    <div class="inf">
      <h3>Telephone</h3>
      <p>{{ user_data.telephone }}</p>
    </div>
    {% if user_data.blocked_at  %}
      <div class="inf">
        <h3>Blocked At</h3>
        <p>{{ user_data.blocked_at }}</p>
      </div>
    {% endif %}
    {% if user_data.inactive_at  %}
      <div class="inf">
        <h3>Deleted At</h3>
        <p>{{ user_data.inactive_at }}</p>
      </div>
    {% endif %}
    <div class="buttons">
      {% if me %}
        <a class="btn btn-primary" href="{% url 'accounts:profile-user-edit' %}">Edit Profile</a>
      {% endif %}
      {% if not user_data.inactive_at %}

        {% if user.is_superuser and not user_data.is_superuser %}
          <a class="btn btn-danger" href="{% url 'accounts:profile-username-delete' username=user_data.username %}"><i class="bi bi-trash-fill"></i> Delete</a>
          {% if user_data.blocked_at %}
            <a class="btn btn-success" href="{% url 'accounts:profile-username-unblock' username=user_data.username %}"><i class="bi bi-unlock-fill"></i> Unlock</a>
          {% else %}
            <a class="btn btn-secondary" href="{% url 'accounts:profile-username-block' username=user_data.username %}"><i class="bi bi-lock-fill"></i> Block</a>
          {% endif %}
        {% endif %}
      {% endif %}
    </div>
  </div>
{% endblock container %}